openapi: 3.0.0
servers:
  - url: 'http://localhost:8000'
info:
  description: >-
    This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: notes
    description: Everything about working with notes
paths:
  /api/notes:
    post:
      tags:
        - notes
      summary: Add a new note to the store
      description: ''
      operationId: addNote
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/Note'
    get:
      tags:
        - notes
      summary: List all notes in the notepad
      description: ''
      operationId: listNotes
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteArray'
        '405':
          description: Invalid input
  '/api/notes/{noteId}':
    delete:
      tags:
        - notes
      summary: Deletes a note
      description: ''
      operationId: deleteNote
      parameters:
        - name: noteId
          in: path
          description: Note id to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Invalid note value
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  requestBodies:
    Note:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NoteBody'
      description: Note object that needs to be added to the store
      required: true
  schemas:
    NoteArray:
      title: Notes Array
      description: an array of Notes
      type: array
      items:
        $ref: '#/components/schemas/Note'
    Note:
      title: a created Note
      description: A note in the notepad
      type: object
      required:
        - id
        - title
        - content
      properties:
        id:
          type: string
          format: uuid
          example: Affjhe837ehsdshjdsj
        title:
          type: string
          example: My cool note
        content:
          type: string
          example: My hometown is near the beach!
    NoteBody:
      title: the body of a Note
      description: A note in the notepad
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          example: My cool note
        content:
          type: string
          example: My hometown is near the beach!
